# Set up your streams to rtsp here.
port: "8554"
streams: # Cannot rename - must leave this as is.

  stream-cam:
    type: topic
    source: /camera/color/image_raw/compressed
    mountpoint: /back
    caps: video/x-raw,framerate=10/1,width=80,height=60
    bitrate: 500

